### ISSUE TITLE
Ambiguous Key Error for keys that are suffix to other keys

### ISSUE THREAD

**Issue by katharinekerr** [kormide/recipe#51]
*Steps to Reproduce*
Key two resources, where one is a suffix of the other, e.g. `AB` and `B`. Then, try to get the `id` of `B`.

For example:
```
Cake cake = oven.bake(Recipe.prepare(
   new mySetup1(...).keyed("B"),
   new mySetup1(...).keyed("AB"),
));

cake.get("B") // throws ambiguous key error
```

*Problem*
I think the problem is how we determine the list of key match candidates in Cake.java: `List<String> candidates = entries.keySet().stream().filter(k -> k.endsWith(fullKey)).collect(Collectors.toList());`.

**Comment by kormide** [comment]
Fixed in https://github.com/kormide/recipe/commit/e781b54d32bb97f0955b8fc204355cf1abdbb45d. Will be released in the next patch.
