### ISSUE TITLE
Not enough information when cake does not contain key or when key is ambigous

### ISSUE THREAD

**Issue by kmccoan-allocadia** [kormide/recipe#60]
In Cake.java L.83 & L.86:
```
else if (candidates.isEmpty()) {
            throw new RuntimeException("cake does not contain key '" + fullKey + "'");
        }
        else {
            throw new RuntimeException("cannot retrieve ambiguous key '" + fullKey + "'");
        }
```

when candidates is empty, can you append the full list of cake keys so it's easier to diagnose what went wrong?

When there are more than one candidates, can you append the list of candidates so it's easy to see why its ambigious?

**Comment by kormide** [comment]
Merged a fix for better exception messages: 5e7404a1a72832ba0f688981f562788ffa21a457. Will be deployed in the next version.
