### ISSUE TITLE
Oven is swallowing the exception messages

### ISSUE THREAD

**Issue by kmccoan-allocadia** [kormide/recipe#61]
Oven.java L.46
```
catch (Exception e) {
            throw new RuntimeException("could not bake cake", e);
        }
```

I'd like to be able to see e's cause message as this is more interesting in debugging purposes than "could not bake cake"

**Comment by kormide** [comment]
Because I'm passing `e` as the cause, the original exception should be printed out in a stack trace where it says "Caused by ...`.
